accounts/urls.py
from django.urls import path
from .views import profile_edit,profile,signUP


app_name = 'accounts'


urlpatterns = [
    path('signUP',signUP,name='signUP'),
    path('profileEdit',profile_edit,name='profileEdit'),
    path('profile/',profile,name = 'myprofile')
]

blog/urls.py
from django.urls import path
from .views import PostList,PostDetails
from .api_view import Blog_list,Blog_details,Blog_search

app_name = 'blog'

urlpatterns = [
    path('', PostList.as_view(),name='BlogList'),
    path('<slug:slug>', PostDetails.as_view(),name='BlogDetails'),


    # API_URLS
    path('api/list', Blog_list,name='BlogAPIList'),
    path('api/<int:pk>', Blog_details,name='BlogAPIDetail'),
    path('api/<str:query>', Blog_search,name='Blog_search'),


]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('property/',include('property.urls',namespace='property')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('about/',include('about.urls',namespace='about')),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace='accounts'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
X_FRAME_OPTIONS = 'SAMEORIGIN'

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver



class Profile(models.Model):
    user = models.ForeignKey(User, related_name="user_profile", on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profile/', null=True, blank=True)
    phone_number = models.CharField(max_length=16, null=True, blank=True)
    address = models.CharField(max_length=50, null=True, blank=True)


    def __str__(self):
        return str(self.user)  
    
    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

accounts/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render
from .models import Profile
from .froms import profile_form, user_form,userCreateForm
from django.urls import reverse
from django.contrib import messages
# Create your views here.


def signUP(request):
    if request.method == "POST":
        userForm = userCreateForm(request.POST)
        if userForm.is_valid():
            userForm.save()
            username = userForm.cleaned_data['username']
            password = userForm.cleaned_data['password1']
            user = authenticate(username = username,password = password)
            login(request,user)
            return redirect(reverse('accounts:myprofile'))

    else:
        userForm = userCreateForm()
    

    return render(request,'profile/singup.html',{'userForm':userForm})




def profile(request):
    profile = Profile.objects.get(user = request.user)
    

    return render(request,'profile/profile.html',{'myprofile':profile})



def profile_edit(request):
    
    profile = Profile.objects.get(user = request.user)
    if request.method == 'POST':
        userForm = user_form(request.POST,instance=request.user)
        profileForm = profile_form(request.POST,request.FILES,instance=profile)
        if userForm.is_valid() and profileForm.is_valid():
            userForm.save()
            myForm = profileForm.save(commit=False)
            myForm.user = request.user
            myForm.save()
            messages.success(request, 'Profile details updated.')
            return redirect(reverse('accounts:myprofile'))
    else:
        userForm = user_form(instance=request.user)
        profileForm = profile_form(instance=profile)
    return render(request,'profile/profile_edit.html',{
        'form_user':userForm,
        'form_profile':profileForm
        })

    

accounts/templates/profile/profile.html
{% extends "base.html" %}
{% load static %}
{% block body %}
<div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_5.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center"
            data-scrollax-parent="true">
            <div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
                <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span
                        class="mr-2"><a href="index.html">Home</a></span> <span class="mr-2"><a
                            href="hotel.html">Hotel</a></span> <span>Hotel Single</span></p>
                <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Hotels Details
                </h1>
            </div>
        </div>
    </div>
</div>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}



<h1>My profile</h1>

<p>{{ myprofile.user.username }}</p>

<p>{{ myprofile.user.email }}</p>

<p>{{ myprofile.phone_number }}</p>

<p>{{ myprofile.address }}</p>



<hr>

<a href="{% url 'accounts:profileEdit' %}"><p>Edit Profile</p></a>
<a href="{% url 'password_change' %}"><p>Password Change</p></a>



{% endblock body %}

accounts/templates/profile/profile_edit.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block body %}
<div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_5.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center"
            data-scrollax-parent="true">
            <div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
                <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span
                        class="mr-2"><a href="index.html">Home</a></span> <span class="mr-2"><a
                            href="hotel.html">Hotel</a></span> <span>Hotel Single</span></p>
                <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Hotels Details
                </h1>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div  class="col-mid-4 mx-auto">
        <h1>Edit Profile</h1>

        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form_user %}
            {% bootstrap_form form_profile %}

            {% buttons %}
            <button type="submit" class="btn btn-primary py-3 m-auto">Edit PRofile</button>
            {% endbuttons %}
        </form>
    </div>
</div>


{% endblock body %}

accounts/templates/profile/singup.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block body %}
<div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_5.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center"
            data-scrollax-parent="true">
            <div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
                <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span
                        class="mr-2"><a href="index.html">Home</a></span> <span class="mr-2"><a
                            href="hotel.html">Hotel</a></span> <span>Hotel Single</span></p>
                <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Hotels Details
                </h1>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div  class="col-mid-4 mx-auto">
        <h1>SignUp</h1>

        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form userForm %}
            {% buttons %}
            <button type="submit" class="btn btn-primary py-3 m-auto">Rest Password</button>
            {% endbuttons %}
        </form>
    </div>
</div>


{% endblock body %}