blog/urls.py
from django.urls import path
from .views import PostList,PostDetails
from .api_view import Blog_list,Blog_details,Blog_search

app_name = 'blog'

urlpatterns = [
    path('', PostList.as_view(),name='BlogList'),
    path('<slug:slug>', PostDetails.as_view(),name='BlogDetails'),


    # API_URLS
    path('api/list', Blog_list,name='BlogAPIList'),
    path('api/<int:pk>', Blog_details,name='BlogAPIDetail'),
    path('api/<str:query>', Blog_search,name='Blog_search'),


]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('property/',include('property.urls',namespace='property')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('about/',include('about.urls',namespace='about')),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace='accounts'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
X_FRAME_OPTIONS = 'SAMEORIGIN'

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(User, related_name='owner_vlog', on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=15000)
    created_at = models.DateTimeField(default=timezone.now)
    imge = models.ImageField(upload_to='blog/')
    category = models.ForeignKey("Category", related_name='Category_blog', on_delete=models.CASCADE)
    tags = TaggableManager(blank=True)
    slug = models.SlugField(null=True,blank=True)

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    def get_absolute_url(self):
        return reverse("BlogDetails", kwargs={"pk": self.pk})
    
    def __str__(self):
        return self.title

    def save(self,*args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        elif self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    
    


class Category(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
    def __str__(self):
        return self.name

blog/views.py
from django.db import models
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from .models import Post,Category
from taggit.models import Tag
# Create your views here.
from django.db.models import Count

class PostList(ListView):
    model = Post
    paginate_by = 8



class PostDetails(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tages"] = Tag.objects.all()
        context['categories'] = Category.objects.all().annotate(post_count= Count('Category_blog'))[:4][:5]
        context["recent_blog"] = Post.objects.all()[:3]
        return context
    

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_5.jpg' %});">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center"
      data-scrollax-parent="true">
      <div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
        <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-2"><a
              href="index.html">Home</a></span> <span>Hotel</span></p>
        <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Hotels</h1>
      </div>
    </div>
  </div>
</div>



<section class="ftco-section ftco-degree-bg">
  <div class="container">
    <div class="row">
      <div class="col-md-8 ftco-animate">
        <h2 class="mb-3">{{post.title}}</h2>
        <p>
          <img src="{{ post.imge.url}}" alt="" class="img-fluid">
        </p>
        <p>{{post.description|safe}}</p>
        <div class="tag-widget post-tag-container mb-5 mt-5">
          <div class="tagcloud">
            {% for tag in post.tags.all %}
            <a href="#" class="tag-cloud-link">{{tag}}</a>
            {% endfor %}
          </div>
        </div>

        <div class="about-author d-flex p-5 bg-light">
          <div class="bio align-self-md-center mr-5">
            <img src="images/person_1.jpg" alt="Image placeholder" class="img-fluid mb-4">
          </div>
          <div class="desc align-self-md-center">
            <h3>Lance Smith</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate
              quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos
              fugit cupiditate numquam!</p>
          </div>
        </div>


        <div id="disqus_thread"></div>

      </div> <!-- .col-md-8 -->
      <div class="col-md-4 sidebar ftco-animate">
        <div class="sidebar-box">
          <form action="#" class="search-form">
            <div class="form-group">
              <span class="icon fa fa-search"></span>
              <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
            </div>
          </form>
        </div>
        <div class="sidebar-box ftco-animate">
          <div class="categories">
            <h3>Categories</h3>
            {% for category in categories %}
            <li><a href="#">{{category}} <span>{{category.post_count}}</span></a></li>
            {% endfor %}

          </div>
        </div>

        <div class="sidebar-box ftco-animate">
          <h3>Recent Blog</h3>
          {% for RecentBlog in recent_blog %}
          <div class="block-21 mb-4 d-flex">
            <a class="blog-img mr-4" style="background-image: url({{RecentBlog.imge.url}});"></a>
            <div class="text">
              <h3 class="heading"><a href="#">RecentBlog.title</a>
              </h3>
              <div class="meta">
                <div><a href="#"><span class="icon-calendar"></span>{{ RecentBlog.created_at |date:"F j Y"}}</a></div>
                <div><a href="#"><span class="icon-person"></span> {{RecentBlog.author}}</a></div>
                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
              </div>
            </div>
          </div>
          {% endfor %}


        </div>

        <div class="sidebar-box ftco-animate">
          <h3>Tag Cloud</h3>
          <div class="tagcloud">
            {% for tagg in tages %}
            <a href="#" class="tag-cloud-link">{{tagg}}</a>
            {% endfor %}


          </div>
        </div>

        <div class="sidebar-box ftco-animate">
          <h3>Paragraph</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate
            quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit
            cupiditate numquam!</p>
        </div>
      </div>

    </div>
  </div>
</section> <!-- .section -->
<script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
    
    var disqus_config = function () {
    this.page.url = "http://127.0.0.1:8000/blog/{{ post.slug }}";  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier ="{{ post.slug }}"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    
    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://airbnb-6.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
{% endblock body %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_5.jpg' %});">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center"
      data-scrollax-parent="true">
      <div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
        <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-2"><a
              href="index.html">Home</a></span> <span>Hotel</span></p>
        <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Hotels</h1>
      </div>
    </div>
  </div>
</div>



<section class="ftco-section bg-light">
  <div class="container">
    <div class="row d-flex">
      {% for post in object_list %}
      <div class="col-md-3 d-flex ftco-animate">
        <div class="blog-entry align-self-stretch">
          <a href="{% url 'blog:BlogDetails' post.slug %}" class="block-20"
            style="background-image: url('{{post.imge.url}}');">
          </a>
          <div class="text p-4 d-block">
            <span class="tag">Tips, Travel</span>
            <h3 class="heading mt-3"><a href="{% url 'blog:BlogDetails' post.slug %}">{{post.title}}</a></h3>
            <div class="meta mb-3">
              <div><a href="#">{{post.created_at |date:"F j Y"}}</a></div>
              <div><a href="#">{{post.author}}</a></div>
              <div><a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a></div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}

    </div>
    {% if is_paginated %}
    <div class="row mt-5">
      <div class="col text-center">
        <div class="block-27">
          <ul>
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
            {% else %}
            <li class="disabled"><span>&lt;</span></li>
            {% endif %}

            {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
            <li class="active"><span>{{ i }} </span></li>
            {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
            {% else %}
            <li class="disabled"><span>&gt;</span></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
    {% endif %}
  </div>
</section>
{% endblock body %}